language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install git+https://github.com/fkie-cad/common_helper_files.git"
  - "pip install ."
  - "pip install -U pytest"
  - "pip install pytest-pep8 pytest-cov codecov"
# command to run tests
script: "pytest --cov-config .coveragerc --cov=./"
after_success:
  - codecov
